[package]
name = "detection_module"
version = "0.1.0"
edition = "2024"

[lib]
name = "detection_module"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
rayon = "1.8"
sha2 = "0.10"
tempfile = "3.3.0"

